services:
  webserver:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    extends:
      file: ./app/docker-compose.yml
      service: php
