services:
  # webserver:
  #   image: nginx:alpine
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - app

  app:
    extends:
      file: ./app/docker-compose.yml
      service: php
    command: php artisan serve --port=80 --host=0.0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - XDEBUG_MODE=develop,debug
    volumes:
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - 80:80
