services:
  webserver:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    extends:
      file: ./app/docker-compose.yml
      service: php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - XDEBUG_MODE=develop,debug
    volumes:
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
