services:
  # webserver:
  #   image: nginx:alpine
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - app

  caddy:
    image: caddy:latest
    volumes:
      - ./.docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - laravel
      - hono

  laravel:
    extends:
      file: ./apps/laravel/docker-compose.yml
      service: php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - XDEBUG_MODE=develop,debug
    volumes:
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - redis

  supervisor:
    extends:
      file: ./apps/laravel/docker-compose.yml
      service: php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: supervisord -c /etc/supervisor/conf.d/supervisord.conf
    environment:
      - XDEBUG_MODE=develop,debug
    volumes:
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./.docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    depends_on:
      - redis

  hono:
    extends:
      file: ./apps/hono/docker-compose.yml
      service: hono
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "6499:6499"
    environment:
      - NODE_ENV=development
    command: bun run dev

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
